# Generated by Django 4.2 on 2024-02-25 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('document', models.FileField(upload_to='document', verbose_name='Документ')),
            ],
            options={
                'verbose_name': 'Документы',
                'verbose_name_plural': 'Документ',
            },
        ),
    ]
