# Generated by Django 4.2 on 2024-03-23 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='tiktok',
            field=models.URLField(blank=True, null=True, verbose_name='Tiktok'),
        ),
    ]
